### ISSUE TITLE
possible compatibility with python's ConfigParser?

### ISSUE THREAD

**Issue by SvenDowideit** [gookit/ini#1]
I've just been doing some Python cfg stuff, and they seem to have a (kinda weird) way to do variable interpolation - see https://docs.python.org/2/library/configparser.html

in essense, strings like `%(VAR_NAME)s` are replaced by the value of `VAR_NAME` - the `s` is significant....

**Comment by inhere** [comment]
Ok, I have added variable parsing support.

- See https://github.com/gookit/ini#variable-reference-resolution
- See the code test for more.

**Comment by SvenDowideit** [comment]
nice!

**Comment by inhere** [comment]
Is this what you want? Can I close this issue?

**Comment by SvenDowideit** [comment]
yeah, sorry - work suddenly got busy on something else, so i've not started storing the settings.

I think the answer is yes thou - thanks!

**Comment by inhere** [comment]
Thank you for your reply!
